// LOCALHOST

### GET main
GET http://localhost:8080

### GET all Items
GET http://localhost:8080/supplies

### POST / Create Item
POST http://localhost:8080/supplies HTTP/1.1
Content-Type: application/json

{
    "sku": "any-001",
    "name": "Milk Powder",
    "description": "any",
    "unit": "ounces",
    "unit_weight": 250,
    "unit_cost": 121.75,
    "stock": 3
}

### GET single item
GET http://localhost:8080/supplies/6516c544e607fc26fbcf1998

### PUT / Update Item
PUT http://localhost:8080/supplies/6516c544e607fc26fbcf1998 HTTP/1.1
Content-Type: application/json

{
    "sku": "put-001",
    "name": "put",
    "description": "put",
    "unit": "lbs",
    "unit_weight": 1,
    "unit_cost": 1,
    "stock": 1
}

### Delete Item
DELETE http://localhost:8080/supplies/6516b9266142857a3dcfb200


### Get all vendors
GET http://localhost:8080/vendor

### Create one vendor
POST http://localhost:8080/vendor HTTP/1.1
Content-Type: application/json

{
    "vendor": "post",
    "address": "post",
    "phone": "123-4567",
    "url": "123.com"
}

### Get one vendor by id
GET http://localhost:8080/vendor/6514fef513ad481905b14c33

### update one vendor
PUT http://localhost:8080/vendor/6516bb3ff527655a357c3e0f HTTP/1.1
Content-Type: application/json

{
    "vendor": "put",
    "address": "put",
    "phone": "123-4567",
    "url": "test.com"
}

### Delete one vendor
DELETE http://localhost:8080/vendor/6516bb95f527655a357c3e10